### ISSUE TITLE
Current work list (ToDo and Ideas)

### ISSUE THREAD

**Issue by andyld97** [andyld97/Home#19]
## Features
- [x] Collect screen infos (Windows only, at the beginning) like display name, resolution, touch points etc. for each dispaly
    - [x] Display each screen (or only on for other Linux or Android) in Home.WPF as a screen icon
    - [x] Make those icons clickable (under Windows not only create one screenshot, but also a screenshot of each display, or maybe a combox in the screenshot viewer?)
- [x] Rework/Clean up GUI
   - [ ] Display battery/storage warnings (#3)
   - [x] Complete localization (#1)
- [ ] Complete smart implementation (#15)
- [ ] Video memory info (#9)
- [x] Home.Service.Windows: Button for creating the autostart script automatically to shell:startup 
- [x] Complete dotnet7 migration (#16)
- [x] No grayscale for `Android`-default image
- [x] Delete device is not working currently
- [x] Determine and display windows product name like this: `Windows 10 Pro x64 (21H2)`
- [x] Fix message decoding in message feature (umlauts)
- [x] Delete Device should notify client-queues with a new `EventQueue-Event` (DeviceDeleted)
- [x] Mention WOL in Feature List (Readme) + Little WOL Tutorial in Wiki (how to setup WOL)
- [x] API File Logging (makes it easier to track exceptions)
- [x] Update to Fluent.Ribbon Alpha v10 (+ Round Corners/W11)
- [x] Config flag (/config) for Home.Service.Windows-Client to enable chaning settings in the gui ("Apply and start service")
- [x] Disable screenshots for a device (via config.json)
- [x] Improve light/white mdoe
- [x] Update to the newest livecharts diagram (breaking changes)
- [x] Home: Total overview enable to show the charts instead of screenshots (maybe with a checkbox for it?)
- [x] Clean up cache of `Home.WPF` (remove old screenshots automatically)
- [x] WOLController EP also accept Device ID as parameter to make it easier
- [x] Detect device name change as a "hardware"-change
- [x] Button Wake UP in Menu where you can select all devices (offline + having a mac address) to wake them up easier
- [X] ~~Make `Home.Windows.Service` as a real Windows-Service (https://learn.microsoft.com/en-us/dotnet/core/extensions/windows-service?pivots=dotnet-7-0)~~ (Doesn't work well, as a service you get wrong display information and cannot make screenshots)
 - [x] Further properties (BIOS Date/Version)
- [x] Config Flag for Allow Remote File Access (client settings)
- [x] Screen report rendering only render &lt;hr&gt; if it's not the last screen
- [x] Also remove the screenshot files from the server! (when deleting a device)
- [x] Display Notifications for Windows 10/11 using Windows Notifications (https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/send-local-toast?tabs=desktop)
 - [x] Improve RefreshDeviceHolder: Only needs to be updated if a device are added/or switched offline/online
 - [ ] Button for clear hardware log
 - [ ] Update signature for .zip/.tar-files (SHA256 Hash)
- [ ] Update screenshots and assets (also for readme) 
- [ ] FreeRAM is a string property (previously used to show it in a TextBlock), but is currently not displayed (activity plot), so change it's type to long and directly store the value instead of a string-text which needs to be parsed!

## Bugs
- [x] UTF-8 Device Names BšRO-RECHNER
- [x] Home.WPF Refreshing (#18)
- [ ] Android no CPU name on Samsung devices (#13)

## Future Ideas
- [X] Wake On LAN (WOL)
    - [X] Possibilty for the user to add a shutdown/boot schedule (e.g. shutdown at 02:00am and boot at 06:00am)
    - [X] It is required to also collect the MAC-adress foreach device?
- [ ] Using a broadcast/unicast to detect API automatically for Clients & Home.WPF (-> Auto Detect Button)
- [ ] Locate android devices with a sound (#10) 
- [ ] Complete Home.Avalonia Impl (Branch: avalonia)

**Comment by andyld97** [comment]
This issue will not be continued anymore (split into multiple issues and Kanban-Board)
